### ISSUE TITLE
Support for hosting existing HTTP serverListeners (like Express apps)?

### ISSUE THREAD

**Issue by lukehoban** [claudiajs/claudia#12]
Claudia appears to currently only support hosting API's defined through the `claudia-api-builder` router API.

I wonder if it would be possible to also support hosting APIs defined by other native Node.js routers, and in particular, popular ones like Express.

I'm imagining something like this - where only the first and last lines are Claudia-specific (and could easily be factored out further if needed).

```js
var ApiBuilder = require('claudia-api-builder')
var express = require('express');
var app = express();

app.get('/', function (req, res) {
  res.send('Hello World!');
});

module.exports = new ApiBuilder(app);
```

There's two components to this:

1. Figuring out how to create the API Gateway routes needed to pass through to the Express API.
2. Building Node `IncomingMessage` and `ServerResponse` objects with sufficiently correct information to invoke the express app as a `requestListener`.

For issue `(1)`, it's likely not possible to extract the routing information accurately enough (and even if you could, it would be framework-specific).  Instead, you could maybe do something like what Zappa does and create general purpose API gateway routes that pass through all calls through to a single router.  See https://github.com/Miserlou/Zappa/blob/master/zappa/zappa.py#L439.  

For issue `(2)`, Zappa again does something similar in creating a WSGI request object out of the request that comes through API gateway.  See https://github.com/Miserlou/Zappa/blob/master/zappa/wsgi.py.  I can't think of any reason this would not in theory be possible for Node's `IncomingMessage`/`ServerResponse` objects.

Thoughts?

**Comment by gojko** [comment]
I'd love to hear what others think about this. 

It's not on a critical path for me, because I don't see Lambda as a good system for serving generic web sites, at least not yet. The latency is not good enough. We use static HTML on CloudFront for that. 

If someone else wants to take a shot at this and implement it in a way that doesn't overcomplicate the API, I'm happy to merge it in. Theoretically, this can be a completely separate project that just returns the correct API config. Claudia deployer only expects a hash map in a particular format.

**Comment by gojko** [comment]
i'm closing this due to lack of community interest; if anyone wants to pick this up in the future, please reopen the issue.
