### ISSUE TITLE
Symbolic links dont get put in zip file

### ISSUE THREAD

**Issue by latourette359** [claudiajs/claudia#124]
Please use GitHub issues only to report bugs. To ask a general question or request assistance/support, please use the [Claudia.js Gitter Chat](https://gitter.im/claudiajs/claudia) instead.

To report a bug or a problem, please fill in the sections below. The more you provide, the better we'll be able to help.

---

* Expected behaviour: 
Recently when trying to use claudia to deploy a sharp project to aws lambda, i came across some behavior that i didn't expect. When zipping dependencies, claudia doesn't seem to package symbolic links. node_modules/sharp/vendors/ relies heavily on symbolic links and therefore could not run when being deployed with claudia (without manual alterations to the dependencies.) I expect these symbolic links should be uploaded.

* What actually happens: symbolic links do not get put into the zip file. 

* Link to a minimal, executable project that demonstrates the problem: 
using claudia to deploy https://github.com/awslabs/serverless-image-resizing

* Steps to install the project: 

* Steps to reproduce the problem:
if you package https://github.com/awslabs/serverless-image-resizing with claudia, node_modules/sharp/vendor/libvipps.so.42 will not be in the upload and therefore the lambda function will not run.

**Comment by latourette359** [comment]
Note: I was able to get it to work by replacing the symbolic links with copies

**Comment by gojko** [comment]
Thanks for reporting this. I've investigated the issue and it seems that the dependent library we use (node-archiver) does not support symlinks yet. They will start will start supporting symlinks in the next major version (https://github.com/archiverjs/node-archiver/issues/243), so when that gets released we can update claudia.

Fixing this now would require either changing the library to use for producing the zip files, or contributing upstream to the node archiver and implementing support for symbolic links. Both are too much work for me to pursue now. If you'd like to contribute, this is the function that needs to change: https://github.com/claudiajs/claudia/blob/master/src/tasks/zipdir.js -- please submit a pull request and I'll merge it.

Including symbolic links should be an option rather than something forced, to avoid system libraries being linked in by mistake. (eg check out https://github.com/serverless/serverless/issues/3215)

**Comment by CameronK** [comment]
archiver/node-archiver#243 has cleared with support for symlinks and node-archiver has bumped up to version 2.0.0.

**Comment by latourette359** [comment]
Great thanks guys.

**Comment by kevintechie** [comment]
This bug should be re-opened because node-archiver still does not handle symlinks correctly, and, therefore, claudiajs doesn't create packages with valid symlinks.

**Comment by stojanovic** [comment]
It's not node-archiver, it's because of `npm pack`. We are aware of this, but we are still deciding if it should be handled because then we can't simply do `npm pack` anymore, and that solves a lot of potential problems.

**Comment by kevintechie** [comment]
Is the issue being tracked someplace? There still seems to be a fix for a bug in node-archiver that hasn't been released yet: https://github.com/archiverjs/node-archiver/pull/293

**Comment by pkyeck** [comment]
can we handle symlinks now? looks like no – still get the error.
