### ISSUE TITLE
add-scheduled-event --schedule parameter can not be parsed in Windows

### ISSUE THREAD

**Issue by philltomlinson** [claudiajs/claudia#20]
When using a windows machine the command to create a lambda scheduled event does not work. If the following is run:

`claudia add-scheduled-event --event test.json --name website-alerts --schedule 'rate(5 minutes)'`

The following error is displayed as windows does not deal with the curly brackets:

`' was unexpected at this time.`

Using ^ escape characters works and windows validates the command but then the AWS service returns with an error that the schedule expression is invalid.

It would be ideal if the --schedule option could be read from the claudia.json file at runtime. Therefore windows users would not need to pass the brackets on the command line.

**Comment by gojko** [comment]
`claudia.json` is not a good solution here because people should be able to add multiple events to multiple versions. I've added the `--rate` option that allows you to specify the rate without the brackets instead of `--schedule`. So it would be something like 

```bash
claudia add-scheduled-event --event test.json --name website-alerts --rate "5 minutes"
```

I assume this will enable windows to parse the argument.  The new version 1.0.11 is on NPM now.
