### ISSUE TITLE
[UX Suggestion] Add a progress spinner via Ora

### ISSUE THREAD

**Issue by aidanbon** [claudiajs/claudia#38]
Claudia behind the scene performs many steps to accomplish her task (e.g. package module, npm install, create role, policy, API Gateway, Lambda, etc, etc.) Since many of these steps involves network connections, which can be time consuming. A typical Claudia operation can take from a few seconds to over 1 minute to complete.

As a user, it will be great if Claudia can keep me inform as she is doing the various tasks. I'm thinking of making use of the _elegant terminal spinner_ module, Ora, by Sindre Sorhus https://github.com/sindresorhus/ora to do this.

I have a draft implementation at: 
https://github.com/aidanbon/claudia/commit/0db54b7fdbb4441d3e4cba00ab9448d7cdd74cc0

Please let me know what you think, should I proceed with a PR.  Thanks.

**Comment by gojko** [comment]
I started putting support for more details with the (for now hidden) option --verbose. most of the time, the execution is in the `rebuildWebApi` section, so the spinner wouldn't help a lot without digging into that. supplying --verbose will log a ton of details about executing AWS SDK requests while building the web api, and it could be abstracted a bit more to support the other APIs as well. 

Ideally, I'd like to avoid binding the code in the create command to a spinner, but provide an external way for the command to report progress, so that the command line execution shell can then say 'I'll display a spinner for this', but if someone runs create or update directly via the JS api, they can handle it differently.  

A+ promises have no notion of .notify, which is one of the things I really miss from jQuery deferreds here. Perhaps a good solution would be to supply options.progress, and in create/update check if that is a function, and if so call it with the status. then that function could be passed to rebuildWebApi instead of a simple verbose flag, and [cmd.js](https://github.com/claudiajs/claudia/blob/master/bin/cmd.js) could set up the ORA spinner as an implementation of that. Would you like to give that a shot?

**Comment by aidanbon** [comment]
Thanks for the feedback! 
I'm not sure I grasp fully your idea. Let me try to reiterate - The essence is **not to tightly couple** the _status messaging_ (be it an Ora spinner, or something else) to the core processing commands (e.g. create, update, etc) and their helper functions (e.g. rebuildWebApi). 

Your suggested approach is let cmd.js (optionally) wrap the status messaging as a function, and pass it down to the processing commands. Inside the processing commands, they simply invoke the passed in messaging function at the appropriate steps to report statuses.

The advantage of this decoupling is to allow complete disabling of status reporting, and/or easily replace with a different reporting agent.

Let me know if I'm on the same page or totally off :)

**Comment by gojko** [comment]
yes, that's the idea. I was thinking a bit more about this, and I think we can make this slightly more generic by allowing the commands to have two arguments - options and reporter function, then cmd.js can set the reporter function based on some external config. this would eg allow for ORA or console log and even define the level of information printed. I'll change the functions tonight to allow for that and we can look into setting up ORA after that

**Comment by aidanbon** [comment]
On the topic of making the reporter decouples from the core processing logic. We can make use of Node [EventEmitter](https://nodejs.org/api/events.html). 

In brief, wrap and export an eventEmitter instance in a helper file (e.g. util/logger.js). All the appropriate processing functions (e.g. create.js, rebuildApi.js, etc) simply require this logger instance, and emit() its status when appropriate. While at cmd.js, it also requires the logger instance, and setup a listener to handle the emitted events. The handler can then have freedom to ignore all these events (in quite mode), or console.log the statuses (in log mode), or ORA out a spinner with status text (in progress mode).

**Comment by gojko** [comment]
I like the EventEmitter idea, but I'd stay away from a singleton instance so that we can test it easier. It should be relatively easy to make the key commands inherit from EventEmitter, and then cmd.js can check if the current command is an EventEmitter and if so, wire up the logging correctly. Then we can also do unit tests for commands emitting the correct events as they execute stuff. I'll try to wire up create tonight like that

**Comment by gojko** [comment]
I got this a bit wrong... it seems EventEmitter is useful when instantiating new objects, but doesn't wrap existing objects easily. So I'll probably introduce an optional second arg to all the commands, an instance of EventEmitter, that they can use to log back the results.

**Comment by gojko** [comment]
@aidanbon it took a bit longer than expected, because I had a few false starts, but `create` and `update` now have a way to log API command execution. I will implement a console listener for that to just dump stuff out tonight, and we can then pick up after that to see how to turn it into a spinner

**Comment by gojko** [comment]
@aidanbon 1.3.0 is now both on NPM and on GitHub, and Claudia logs command execution to the console while working for `create` and `update`. I'll add this behaviour to the other commands as well. Does this give you what you needed, or would you still prefer to add a spinner there? If so, we can implement a new Logger (check out the ConsoleLogger in src/util) and wire it up to cmd.js

**Comment by aidanbon** [comment]
Thanks @gojko! 
Your enhancement looks good. I like the way you wrap the log function within a Logger class (ConsoleLogger in this case). This make swapping with a different Logger class pretty straight forward (or even replace with a different loggable object for ConsoleLogger).

I think the current console.log output format and level of details is sufficient, it totally serves the purposes of progress update, as well as debugging. Unless someone else desire a spinner, I think you can close this issue.  Thanks again for your effort!
