### ISSUE TITLE
aws-sdk could be pruned from zip files

### ISSUE THREAD

**Issue by scottbessler** [claudiajs/claudia#44]
Currently, if your lambda uses aws-sdk, and many do, it will end up in the pushed code, even tho the lambda workers have it pre-installed.

Currently the only option I came up with was to make it a devDependency so that it isn't included, but this generally will fail the validation step that require's your handler. So then you need to hack it as an optional dependency or somesuch.

Given this tool is lambda specific it seems reasonable to have an option that hunts down and removes node-modules/aws-sdk after validating and before zipping.

If I create a PR for this, is this something that you are interested in? Is it best to make it an option of the update command?

**Comment by gojko** [comment]
I think this is a nice thing to add as an option, so a PR would be good. By default, I think the aws-sdk library should stay in the package, because then I know exactly that my deployed version is going to match the one I tested. 

I guess introducing another step after validating the package and before zipping the dir (eg around https://github.com/claudiajs/claudia/blob/master/src/commands/create.js#L230 and https://github.com/claudiajs/claudia/blob/master/src/commands/update.js#L54) based on an option would be good.

**Comment by gojko** [comment]
i'm closing this one due to lack of activity. if anyone wants to pick it up, please submit a pull request
