### ISSUE TITLE
Problems using sqlite with claudiajs

### ISSUE THREAD

**Issue by xavicolomer** [claudiajs/claudia#94]
Hi there,

I am having some problems using sqlite3 with claudiajs, the app works fine locally but when uploading it to API gateway I get:
`{"message": "Internal server error"}`

Cloudwatch translates to:
```
Unable to import module 'lambda': Error
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/var/task/node_modules/sqlite3/lib/sqlite3.js:4:15)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
```

And possibly the line causing this is:
`const db = new sqlite3.Database(path.join(__dirname, '../path/to/db'));`

I have run the command
`npm pack --production `

and checked the db file was correctly placed in the folder.

Any ideas?

**Comment by stojanovic** [comment]
The only place you can write is `/tmp`, your sqlite db would be read only anyway. Beside that it would not be consistent because there's no guarantee that you'll run the same server at your second request. Consider using other db or at least other way to store your sqlite file.

This error can be unrelated to sqlite, it says "Unable to import module 'lambda'", so it seems that your lambda module is not exporting a handler.

This doesn't sound like a Claudia bug, please use gitter for questions to get help with the code: http://gitter.im/claudiajs/claudia.

**Comment by gojko** [comment]
hi, this looks as an import problem, not a bug in claudia. please use the gitter channel for general discussions https://gitter.im/claudiajs/claudia
